server:
  port: 8001

spring:
   datasource:
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/mybatis
    username: root
    password: 123456
logging:
  level:
   root: warn
   com.lxh.mapper: trace
  pattern:
   console: '%p%m%n'









